FROM eclipse-temurin:21-jdk

ENV GRADLE_USER_HOME=/gradle-cache

WORKDIR /workspace

COPY gradlew settings.gradle build.gradle gradle.properties ./
COPY gradle ./gradle
RUN chmod +x gradlew && ./gradlew dependencies --no-daemon

COPY src ./src
COPY dev-entrypoint.sh ./dev-entrypoint.sh

EXPOSE 8080

CMD ["sh", "./dev-entrypoint.sh"]
